#!/bin/sh

# Increase repeat rate
xset r rate 300 50

# Change N tilde key
xmodmap -e 'keycode 47 = 0xfe53 0x007e'

# Do not disable mouse while typing (not really a remap...)
xinput set-prop 12 375 0
